name: Build Presentation
on:
  push:
    branches: [ main ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          make
        name: LaTeX Build

