name: Build Presentation
on:
  push:
    branches: [ main ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          make
        name: LaTeX Build
      - name: Commit
        run: |
          git add github.pdf
          git commit -m "Updated presentation PDF."
          git push origin master

