jobs:
  container:
    runs-on: ubuntu-latest
    container: texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          make
        name: LaTeX Build

